In [9]:
import numpy as np

a1 = np.arange(30).reshape(3,5,2)
print(a1,a1.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]] (3, 5, 2)


In [7]:
a2 = np.sum(a1, axis = 0)
print(a2,a2.shape)

[[30 33]
 [36 39]
 [42 45]
 [48 51]
 [54 57]] (5, 2)


In [10]:
a3 = np.sum(a1, axis = 2)
print(a3,a3.shape)

[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]] (3, 5)


In [13]:
a4 = np.sum(a1, axis = 1)
print(a4,a4.shape)

[[ 20  25]
 [ 70  75]
 [120 125]] (3, 2)


In [18]:
from matplotlib import image
image = matplotlib.image.imread('dog.jpg')
print(image.shape)

(1197, 1200, 3)
