In [2]:
# list
lista = []
print(lista)

lista.append('a')
print(lista)

[]
['a']


In [21]:
#numpy ndarray

import numpy as np

array1 = np.array(lista)
print(array1)
array2 = np.array([1,2,3,4])
array3 = np.array([x for x in range(5)])
print(array3)

print(array3,type(array3))

print(array3[[1,4]])
filter1 = array3%2 == 0
print(array3[filter1])
print(array3[array3>2])

['a']
[0 1 2 3 4]
[0 1 2 3 4] <class 'numpy.ndarray'>
[1 4]
[0 2 4]
[3 4]


In [26]:
# for , if 

# for i in array3:
#     print(i)

# for i in range(5): # np.arange(5)랑 같음
#     print(i)

for i in range(5):
    if i > 2:
        print(i)
        
print(array3[array3>2])

3
4
[3 4]


In [30]:
#function

def function_name(n):
    return n*10
    
return_value = function_name(10)
print('return_value : ',return_value)


assert function_name(100) == 1000


return_value :  100


In [76]:
import random

random.seed(123)
listb = []
for i in range(10):
    listb.append(random.randint(0,100))
print(listb)
      
listc = [random.randint(0,100) for _ in range(10)] # 
print(listc)

list_np = np.array(listb)
list_np[list_np>50]
print(len(list_np[list_np>50]))

[6, 34, 11, 98, 52, 34, 13, 4, 48, 68]
[71, 42, 43, 6, 20, 17, 43, 71, 42, 89]
3
