In [5]:
import numpy as np

a1 = np.array([[1,2,3],[10,20,30]])
print(a1)
print(a1.ndim) #2차원 배열
print(a1.shape) #
print(a1.size)

[[ 1  2  3]
 [10 20 30]]
2
(2, 3)
6


In [9]:
a2 = np.arange(20).reshape(4,5)  # reshape 으로 1차원 배열을 2차원 배열로 재구성할 수 있음
print(a2)
print(a2.shape)  #(20,) #1차원 배열

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [13]:
a3 = a2.flatten()  # 2차원 배열 → 1차원 배열 
a3[3] = 100
print(a3)
print(a2)


a4 = a2.ravel()  # flatten() 과 rabel()의 차이 
a4[3] = 200
print(a4)
print(a2)


[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[  0   1   2 200   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [38]:
a2 = np.arange(20).reshape(4,5)
print(a2)
print(a2[1,2])
print(a2[:,1])
print(a2[:,1:4])   # start, stop
print(a2[:,1:4:2]) # start, stop, step
print(a2[1:3,:])
print(a2[::2,:])
print(a2[::2,1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
7
[ 1  6 11 16]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[[ 1  2  3]
 [11 12 13]]


In [45]:
a2 = np.arange(20).reshape(4,5)
print(a2)
#print(a2.shape) #axis

print(a2.sum())
print(a2.sum(axis=0))
print(a2.sum(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
190
[30 34 38 42 46]
[10 35 60 85]


In [48]:
print(a2,a2.shape)
a3 = a2.T
print(a3,a3.shape)
a4 = np.moveaxis(a2,[0],[1])
print(a4,a4.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [68]:
a10 = np.arange(5,20).reshape(3,5)
#print(a10,a10.shape)


# shape(3,5) 의 2차원 ndarray만들기

a11 = (a10[:,2:4])
print(a11.shape)
print(a11.sum(axis=0))

(3, 2)
[36 39]


In [73]:
print(a11)
print('a11의 평균:',np.mean(a11))

[[ 7  8]
 [12 13]
 [17 18]]
a11의 평균: 12.5


In [86]:
a1 = np.arange(0,10).reshape(2,5)
a2 = np.arange(100,110).reshape(2,5)
print(a1)
print(a2)

a3 = np.concatenate((a1,a2),axis = 1) #2차원 배열
print(a3)

a4 = np.hstack((a1,a2)) # 수평
print(a4)

a5 = np.vstack((a1,a2)) # 수직
print(a5)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100 101 102 103 104]
 [105 106 107 108 109]]
[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100 101 102 103 104]
 [105 106 107 108 109]]


In [95]:
#print(a4)
a6 = np.hsplit(a4,5)
print(a6)

[array([[0, 1],
       [5, 6]]), array([[2, 3],
       [7, 8]]), array([[  4, 100],
       [  9, 105]]), array([[101, 102],
       [106, 107]]), array([[103, 104],
       [108, 109]])]


In [98]:
a7 = a4.T
print(a7)
np.vsplit(a7,5)

[[  0   5]
 [  1   6]
 [  2   7]
 [  3   8]
 [  4   9]
 [100 105]
 [101 106]
 [102 107]
 [103 108]
 [104 109]]


[array([[0, 5],
        [1, 6]]),
 array([[2, 7],
        [3, 8]]),
 array([[  4,   9],
        [100, 105]]),
 array([[101, 106],
        [102, 107]]),
 array([[103, 108],
        [104, 109]])]

In [104]:
a2 = np.arange(20).reshape(4,5)
print(a2)

filter1 = (a2[:,0]%10==5)
print(a2[filter1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
