In [20]:
import matplotlib.pyplot as plt
import numpy as np

np.set_printoptions(precision=5, suppress=True)

def my_split(s):
    block_start = False
    start_index = 0
    ret_list=[]
    for i, c in enumerate(s):
        if block_start==False:
            if c==',':
                ret_list.append(s[start_index:i])
                start_index=i+1
            elif c=='"':
                block_start=True
                start_index = i
        else:
            if c=='"':
                block_start=False
    if s[-1]!=',':
        ret_list.append(s[start_index:])
    return ret_list

def check_split(list_data):
    t = set()
    for e in list_data:
        t.add(len(e))
    return len(t)

In [21]:
def np_data_from_data_go_kr_csv(filename):
    t = []
    with open (filename, encoding = 'cp949') as f:
        for line in f:
            t.append(my_split(line[:-1]))
        if check_split(t) != 1:
            return None
        else:
            return np.array(t)
        
def print_index_title(np_data):
    for e in enumerate(np_data[0]):
        print(e)

In [22]:
def target1(data):
    sub_data = np_data[1:,[13,17]]
    sub_data[sub_data=='0']=''
   #sub_data = np.where(sub_data=='0','',sub_data)
    filter1 = sub_data[:,1]!=''
    sub_data_f = sub_data[filter1].astype(np.float64)
    #print(np.unique(sub_data_f[:,0]))
    #print(np.unique(sub_data_f[:,1]))
    #print(sub_data_f[:10])
    
    
    
    filter2 = sub_data_f[:,0]<100
    sub_data_f2 = sub_data_f[filter2]
    
    #_,axe = plt.subplots()
    #axe.scatter(sub_data_f2[:,0],sub_data_f2[:,1])
    
    return np.corrcoef(sub_data_f2[:,0],sub_data_f2[:,1])[0,1]

#target1(np_data)

In [23]:
def target2(data):
    sub_data = np_data[1:,7]
    val,cnt = np.unique(sub_data,return_counts=True)
    #print(val,cnt)
    return cnt[2]*100/np.sum(cnt[1:])
#target2(np_data)

In [24]:
def target3(data):
    sub_data = np_data[1:,[11,7]]
    #print(np.unique(sub_data[:,0]))
    #print(np.unique(sub_data[:,1]))
    t = []
    for e in np.unique(sub_data[:,0]):
        filter1 = sub_data[:,0]==e
        sub_data_f = sub_data[filter1]
        #print(sub_data_f)
        sub_data_f_y = sub_data_f[sub_data_f[:,1]=='Y']
        sub_data_f_n = sub_data_f[sub_data_f[:,1]=='N']
        #print(e, len(sub_data_f_y),len(sub_data_f_n))
        #print(np.unique(sub_data_f[:,1],return_counts=True))
        #print(len(sub_data_f_y)/len(sub_data_f))
        
        yes_count = len(sub_data_f_y)
        no_count = len(sub_data_f_n)
        yes_no_count = yes_count+no_count
        if yes_no_count==0:
            yes_no_count=1
        t.append((e,yes_count, no_count, yes_count/yes_no_count))
    t = np.array(t).astype(np.float64)
    t = np.array(sorted(t,key=lambda x:x[0]))
    return t
        
        
#target3(np_data)

In [25]:
def target4(data):   # 11, 14
    sub_data = np_data[1:,[11,14]]
    sub_data[sub_data=='n']='N'
    sub_data[sub_data=='y']='Y'
    #print(np.unique(sub_data[:,0]))
    #print(np.unique(sub_data[:,1]))


    t = []
    for e in np.unique(sub_data[:,0]):
        filter1 = sub_data[:,0]==e
        sub_data_f = sub_data[filter1]
        #print(sub_data_f)
        sub_data_f_y = sub_data_f[sub_data_f[:,1]=='Y']
        sub_data_f_n = sub_data_f[sub_data_f[:,1]=='N']
        #print(e, len(sub_data_f_y),len(sub_data_f_n))
        #print(np.unique(sub_data_f[:,1],return_counts=True))
        #print(len(sub_data_f_y)/len(sub_data_f))
        
        yes_count = len(sub_data_f_y)
        no_count = len(sub_data_f_n)
        yes_no_count = yes_count+no_count
        if yes_no_count==0:
            yes_no_count=1
        t.append((e,yes_count, no_count, yes_count/yes_no_count))
    t = np.array(t).astype(np.float64)
    t = np.array(sorted(t,key=lambda x:x[0]))
    return t
        
        
#target4(np_data)

In [26]:
def target5(data):   # 11, 16
    sub_data = np_data[1:,[11,16]]
    sub_data[sub_data=='n']='N'
    sub_data[sub_data=='y']='Y'
    #print(np.unique(sub_data[:,0]))
    #print(np.unique(sub_data[:,1]))


    t = []
    for e in np.unique(sub_data[:,0]):
        filter1 = sub_data[:,0]==e
        sub_data_f = sub_data[filter1]
        #print(sub_data_f)
        sub_data_f_y = sub_data_f[sub_data_f[:,1]=='Y']
        sub_data_f_n = sub_data_f[sub_data_f[:,1]=='N']
        #print(e, len(sub_data_f_y),len(sub_data_f_n))
        #print(np.unique(sub_data_f[:,1],return_counts=True))
        #print(len(sub_data_f_y)/len(sub_data_f))
        
        yes_count = len(sub_data_f_y)
        no_count = len(sub_data_f_n)
        yes_no_count = yes_count+no_count
        if yes_no_count==0:
            yes_no_count=1
        t.append((e,yes_count, no_count, yes_count/yes_no_count))
    t = np.array(t).astype(np.float64)
    t = np.array(sorted(t,key=lambda x:x[0]))
    return t
        
        
#target5(np_data)

In [27]:
if __name__ == '__main__':
    np_data = np_data_from_data_go_kr_csv('xing.csv')
    print(target1(np_data))
    print(target2(np_data))
    print(target3(np_data))
    print(target4(np_data))
    print(target5(np_data))
    #print_index_title(np_data)
  

0.5691244290555937
13.534760926958052
[[    0.          0.          2.          0.     ]
 [    1.        423.       6166.          0.0642 ]
 [    2.        859.      12472.          0.06444]
 [    3.        489.       2055.          0.19222]
 [    4.       1002.       4662.          0.17691]
 [    5.        525.       1573.          0.25024]
 [    6.        593.       1460.          0.28885]
 [    7.        371.        584.          0.38848]
 [    8.        166.        334.          0.332  ]
 [    9.        125.        123.          0.50403]
 [   10.         39.         37.          0.51316]
 [   11.         12.          6.          0.66667]
 [   12.          7.          2.          0.77778]
 [   13.          3.          0.          1.     ]
 [   15.          0.          0.          0.     ]]
[[    0.          2.          0.          1.     ]
 [    1.        432.       8104.          0.05061]
 [    2.       3782.      15640.          0.19473]
 [    3.       1848.       1747.          0