In [79]:
import requests
import numpy as np

x = requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')


In [80]:
raw_data = []
for line in x.text.split('\n'):
    raw_data.append(line.split(','))

#print(raw_data)
    
    for sample in raw_data:
        if len(sample) < 1: # 빈줄 방지 
            continue
        for i, value in enumerate(sample[:4]):
            try:
                sample[i] = float(value)
            except:
                sample[i] = 0.0
                

In [81]:
print(raw_data[:20])

[[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'], [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'], [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'], [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'], [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'], [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'], [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'], [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'], [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'], [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'], [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'], [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'], [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'], [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'], [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'], [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'], [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'], [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'], [5.1, 3.8, 1.5, 0.3, 'Iris-setosa']]


 ### 문자열 -> 숫자
- Iris Setosa -> 0
- Iris Versicolour -> 1
- Iris Virginica -> 2
np_data = np.array(raw_data)

In [82]:
for sample in raw_data:
    if len(sample)<2:  # 빈줄 방지 
        continue
    if 'setosa' in  sample[-1] :
        sample[-1] = 0.0
    elif 'versicolor' in sample[-1]:
        sample[-1] = 1.0
    elif 'virginica' in sample[-1]:
        sample[-1] = 2.0
        
        

In [83]:
print(raw_data[0])
print(raw_data[51])
print(raw_data[101])



[5.1, 3.5, 1.4, 0.2, 0.0]
[6.4, 3.2, 4.5, 1.5, 1.0]
[5.8, 2.7, 5.1, 1.9, 2.0]


In [85]:
print(raw_data[-3:])
print(len(raw_data))
raw_data = raw_data[:150]


[[5.9, 3.0, 5.1, 1.8, 2.0], [0.0], [0.0]]
152


In [86]:
print(len(raw_data))


150


In [88]:
np_data = np.array(raw_data)
np_data.shape
np_data[:3]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

### 기본 통계값
- 전체(150샘플) 평균, 표준편차 -sepal length, sepal width, petal length, petal width 
- 품종별(50개씩) 품종별 평균, 표준편차
- 평균 np.mean()
- 표준편차 np.std()

In [125]:
#print(np_data.shape) #150, 5
#print(np_data.sum(axis=0))
print(np_data.mean(axis = 0))
print(np_data.std(axis = 0))

print(np.corrcoef(np_data.T)) #상관도

[5.84333333 3.054      3.75866667 1.19866667 1.        ]
[0.82530129 0.43214658 1.75852918 0.76061262 0.81649658]
[[ 1.         -0.10936925  0.87175416  0.81795363  0.78256123]
 [-0.10936925  1.         -0.4205161  -0.35654409 -0.4194462 ]
 [ 0.87175416 -0.4205161   1.          0.9627571   0.94904254]
 [ 0.81795363 -0.35654409  0.9627571   1.          0.95646382]
 [ 0.78256123 -0.4194462   0.94904254  0.95646382  1.        ]]


In [126]:
#print(np_data.shape)

#print(np_data)
n1 = []
n2 = []
n3 = []


n1 = np_data[:50]
#print(len(n1))
print(n1.mean(axis = 0))
print(n1.std(axis = 0))

n2 = np_data[50:100]
#print(len(n2))
print(n2.mean(axis = 0))
print(n2.std(axis = 0))

n3 = np_data[100:150]
#print(len(n3))
print(n2.mean(axis = 0))
print(n2.std(axis = 0))


[5.006 3.418 1.464 0.244 0.   ]
[0.34894699 0.37719491 0.17176728 0.10613199 0.        ]
[5.936 2.77  4.26  1.326 1.   ]
[0.51098337 0.31064449 0.46518813 0.19576517 0.        ]
[5.936 2.77  4.26  1.326 1.   ]
[0.51098337 0.31064449 0.46518813 0.19576517 0.        ]


In [129]:
filter_setosa = np_data[:,-1] == 0.0
filter_versicolor = np_data[:,-1] == 1.0 
filter_virginica =np_data[:,-1] == 2.0

print(np.mean(np_data[filter_setosa], axis = 0))
print(np.std(np_data[filter_setosa], axis = 0))

names = ['setosa', 'versicolor', 'virginica']

for i in range(3):
    filter = np_data[:,-1]==float(i)
    print(names[i], np.mean(np_data[filter], axis = 0))
    print(names[i], np.std(np_data[filter], axis = 0))
    

[5.006 3.418 1.464 0.244 0.   ]
[0.34894699 0.37719491 0.17176728 0.10613199 0.        ]
setosa [5.006 3.418 1.464 0.244 0.   ]
setosa [0.34894699 0.37719491 0.17176728 0.10613199 0.        ]
versicolor [5.936 2.77  4.26  1.326 1.   ]
versicolor [0.51098337 0.31064449 0.46518813 0.19576517 0.        ]
virginica [6.588 2.974 5.552 2.026 2.   ]
virginica [0.62948868 0.31925538 0.54634787 0.27188968 0.        ]
