In [11]:
import numpy as np

In [15]:
my_np = np.array([1,2,3],[4,5,6],[7,8,9])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [20]:
my_list = [1,2,3,4]
my_list2 = [[1,2,3],[4,5,6]]
arr1 = np.array(my_list)
arr2 = np.array(my_list2)

arr1.shape
arr2.shape

(2, 3)

In [31]:
arr_list = [[1,2,3],[4,5,6],[7,8,9]]
print(arr_list[0][2])
print(arr_list[2][0])

3
7


In [35]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])



In [40]:
arr_2d[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [45]:
arr = np.array([10,20,30,40,50])

arr[1]

arr[[0,2,4]]

array([10, 30, 50])

In [48]:
np.arange(start=1, stop=11, step=1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr = np.array([4,1,5,7,6,3,9,2,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.sort(arr)[::-1]
arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr_2d = np.array([[15,5,20,10],[9,3,6,12],[8,4,6,2]])
print(arr_2d)

np.argsort(arr_2d, axis=1)

[[15  5 20 10]
 [ 9  3  6 12]
 [ 8  4  6  2]]


array([[1, 3, 0, 2],
       [1, 2, 0, 3],
       [3, 1, 2, 0]], dtype=int64)